spring.application.name=ecommerce

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=DB_USERNAME
spring.datasource.password=DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=JWT_KEY

stripe.api.secretKey=STRIPE_TEST_SECRET_KEY





